### ISSUE TITLE
Picker

### ISSUE THREAD

**Issue by Defqon8** [HowestNMCT-18-19-DEVPROGII/L03-Defqon8#1]
https://github.com/HowestNMCT-18-19-DEVPROGII/L03-Defqon8/blob/16528eb6e3bd60706bfc905b11426a6d73bd27ad/Ex02/Ex02/Ex02/Model/Major.cs#L126-L131
`Waarom kan ik geen Add gebruiken wanneer ik nu mijn categorieen in mijn picker (pickCategories) steken

**Comment by LiesPinket** [comment]
De code waarnaar je verwijst zit in je Major klasse. Je picker daarentegen zit in de mainpage. Die twee zijn van elkaar gescheiden en dat is maar goed ook; ik wil straks de major klasse kunnen meenemen naar een totaal andere UI (daarom zelfs geen Xamarin), en ze moet nog steeds werken.

Je slaat dus een stap over. Ik probeer je op weg te helpen met de juiste werkwijze:

1. GetUniqueCategories moet een extra parameter (= tussen de haakjes) mee krijgen die de volledige lijst van Majors bevat. Daaruit filtert hij de unieke categorieën en geeft ze terug:
    `public static list<string> GetUniqueCategories( List<Major> allMajors )`
    --> met je foreach loop loop je door allMajors
    --> voor elke major in die loop controleer je of de categorie ván die major al in result zit, zonee, dan voeg je die toe 
    --> kijk zeker eens naar de demo's indien bovenstaande stappen je niet duidelijk lijken

2. vanuit mainpage.xaml.cs roep je GetUniqueCategories aan:
    --> je geeft de volledige lijst van majors mee aan de functie
    --> je vangt het resultaat op in een lijst van strings (zie terugkeertype GetUniqueCategories)
    --> nu kan je wel je picker aanspreken om alle categorieën aan toe te voegen

Indien bovenstaande een oplossing is voor je probleem mag je deze issue sluiten. In het andere geval: twijfel niet om ons terug te contacteren.
